version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "50000:50000"
    user: root      
    volumes:
      # local time
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
      - "./jenkins:/var/jenkins_home"  
      # for docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$(which docker):/usr/bin/docker"
    networks:
      - jenkins-network      
  nginx:
    image: nginx:stable
    container_name: nginx
    depends_on:
      - jenkins
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx"
    networks:
      - jenkins-network  
networks:
  jenkins-network:
    driver: bridge
    ipam:
      config:
        - subnet:  192.168.0.1/24